spring:
  #连接池
  datasource:
    #阿里数据库连接池
    druid:
      db-type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&useSSL=false
      username: root
      password: 123456
      max-active: 20
      initial-size: 1
      max-wait: 60000
  #热部署配置
  devtools:
    restart:
      enabled: true
      additional-paths:
      - src/main/java
#mybatis设置
mybatis:
  mapper-locations:
  - /mybatis/*Mapper.xml
  type-aliases-package: net.cyys.entity
#tomcat相关配置
server:
  port: 8888